apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-website
  labels:
    app: bad-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bad-website
  template:
    metadata:
      labels:
        app: bad-website
    spec:
      terminationGracePeriodSeconds: 2
      containers:
        - name: bad-website
          image: bad-website:latest
          imagePullPolicy: Never # for local development - don't ask
          ports:
            - containerPort: 5001
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5001
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5001
            periodSeconds: 3
