apiVersion: v1
kind: Service
metadata:
  name: bad-website
spec:
  type: NodePort
  selector:
    app: bad-website
  ports:
    - protocol: TCP
      name: http
      port: 5001
      targetPort: 5001
      nodePort: 31001
