apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-website
  labels:
    app: good-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: good-website
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: good-website
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: good-website
          image: good-website:latest
          imagePullPolicy: Never # for local development - don't ask
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            periodSeconds: 3
