apiVersion: v1
kind: Service
metadata:
  name: good-website
spec:
  type: NodePort
  selector:
    app: good-website
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000
      nodePort: 31000
